language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 8
after_success:
  - npm install -g semantic-release
  - semantic-release pre && npm publish && semantic-release post
  - npm install --no-save semantic-release
  - npx travis-deploy-once "semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
